# Poprawiona składnia i dodane komentarze
trigger:
  branches:
    include:
      - master  # Rekomendowana zmiana na 'main', jeśli używasz nowszej konwencji nazewnictwa

pr:
  branches:
    include:
      - '*'

jobs:
- job: BuildImages
  displayName: 'Build Docker images dynamically'
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: AWSShellScript@1
    displayName: 'Check AWS CLI version' # Bardziej opisowa nazwa kroku
    inputs:
      # WAŻNE: Zastąp 'Your-AWS-Service-Connection' rzeczywistą nazwą swojego połączenia usług AWS
      regionName: 'eu-west-1'
      scriptType: 'inline'
      inlineScript: |
        echo "Sprawdzanie wersji AWS CLI..."
        kubectl --version